# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - 
        name: Checkout
        uses: actions/checkout@v2
    -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
    -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
    -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          # username: ${{ secrets.DOCKERHUB_USERNAME }}
          username: "ngbao245"
          password: "Baobibo@03"      
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true