name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-package:
    runs-on: ubuntu-latest

    steps:
      - name: Clean
        run: dotnet clean

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Run Tests
        run: dotnet test

      - name: Build
        run: dotnet build

      - name: Publish
        run: dotnet publish -c Release -o ./publish

      - name: Docker Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: your-docker-registry/your-image-name:latest
